### ISSUE TITLE
Unable to train an Object Detection model using an AugmentedManifestFile 

### ISSUE THREAD

**Issue by dsulkin** [awslabs/amazon-sagemaker-examples#643] opened 2019-02-25 21:20 UTC
I'm running into problems training an Object Detection model using an AugmentedManifestFile that was outputted from GroundTruth.  

I have followed the following examples using the console and the Jupyter notebook.

- https://docs.aws.amazon.com/sagemaker/latest/dg/augmented-manifest.html

- https://github.com/awslabs/amazon-sagemaker-examples/blob/master/ground_truth_labeling_jobs/object_detection_augmented_manifest_training/object_detection_augmented_manifest_training.ipynb

I have ended up with different errors depending on which configuration I use.  Below is the collection of configurations and their associated errors I am seeing.  

I have tried doing this in a Jupyter notebook but am ending up with the same combination of errors.

I am running out of ideas and would really like to get this working.  How can I use an augmented manifest file that has been generated from GroundTruth to train a model?  

Here is a sample of the manifest file:
{"source-ref":"s3://XXXXXX/images/538906508f247.image.jpg","hazmat-job":{"annotations":[],"image_size":[{"width":444,"depth":3,"height":288}]},"hazmat-job-metadata":{"job-name":"labeling-job/hazmat-job","class-map":{},"human-annotated":"yes","objects":[],"creation-date":"2019-02-18T17:11:16.729200","type":"groundtruth/object-detection"}}

Below are configurations and their errors:

**Common Configuration**
-  Algorithm source: Amazon SageMaker built-in algorithm
- Choose an algorithm: Object Detection
- Input Mode: Pipe
- Hyperparameters - Used the default and filled in 1 for num_classes and 1 for num_training_samples

**Configuration 1**
-  Channel Name: "train" or "validation" (i create depending on the channel
-  Input Mode: Pipe
-  Content-Type: left this blank
-  Compression type: None
-  Record Wrapper: RecordIO
-  S3 Data Type: AugmentedManifestFile
-  S3 Data Distribution type: FullyReplicated
- Augmented Manifest File Attribute Names:  hazmat-job

**Error**
-  ClientError: Invalid image found. Please ensure data is in one of the expected image formats 

**Configuration 2**
-  Channel Name: "train" or "validation", depending on the channel
-  Input Mode: Pipe
-  Content-Type: left this blank
-  Compression type: None
-  Record Wrapper: RecordIO
-  S3 Data Type: AugmentedManifestFile
-  S3 Data Distribution type: FullyReplicated
- Augmented Manifest File Attribute Names:  source-ref and hazmat-job

**Error**
-  ClientError: Got empty batch from pipe. Please check if the manifest file contains valid batches and the value of training job parameter AttributeNames matches attributes names in the augmented manifest.

**Configuration 3**
-  Channel Name: "train" or "validation", depending on the channel
-  Input Mode: Pipe
-  Content-Type: application/x-recordio
-  Compression type: None
-  Record Wrapper: RecordIO
-  S3 Data Type: AugmentedManifestFile
-  S3 Data Distribution type: FullyReplicated
- Augmented Manifest File Attribute Names:  source-ref and hazmat-job

**Error**
-  ClientError: ClientError: Got empty batch from pipe. Please check if the manifest file contains valid batches and the value of training job parameter AttributeNames matches attributes names in the augmented manifest.

**Configuration 4**
-  Channel Name: "train" or "validation", depending on the channel
-  Input Mode: Pipe
-  Content-Type: application/x-image
-  Compression type: None
-  Record Wrapper: RecordIO
-  S3 Data Type: AugmentedManifestFile
-  S3 Data Distribution type: FullyReplicated
- Augmented Manifest File Attribute Names:  source-ref and hazmat-job

**Error**
-  ClientError: ClientError: ClientError: train channel is not specified.

**Configuration 5 - Based on a solution from AWS forum post**
-  Channel Name: "train" or "validation", depending on the channel
-  Input Mode: Pipe
-  Content-Type: application/x-image
-  Compression type: None
-  Record Wrapper: RecordIO
-  S3 Data Type: S3Prefix
-  S3 Data Distribution type: FullyReplicated
- Augmented Manifest File Attribute Names:  source-ref and hazmat-job

**Error**
-  ClientError: ClientError: train channel is not specified.

**Comment by natsirtguy** [comment] 2019-02-26 00:51
Your Configuration 3 looks right.

The problem is most likely that the annotation in your single training example is empty. There has to be at least one non-empty annotation in the minibatch for the training to work, I believe.

Are there any lines in your manifest file that have nonempty annotations, i.e. that don't have 

"annotations":[]

in them, and instead have a nonempty list there? If so, try making another manifest file with only those entries and see if it works.

**Comment by dsulkin** [comment] 2019-02-26 16:02
Great, thank you.  

Yes, I see both empty and nonempty annotations.  I made 2 new manifest files with a small sample of only nonempty annotations and that does work.  I'm going to increase the min_batch_size hyper parameter to see how that impacts my tests and then also look at making a train manifest file with only nonempty annotations.

Do you know how many nonempty annotations I need within a given mini batch?  Should there be a percent I am looking to achieve?

**Comment by natsirtguy** [comment] 2019-02-26 17:50
Awesome, I'm glad it worked!

Actually, it turns out that the total number of nonempty annotations in your manifest file needs to be strictly greater than the mini_batch_size hyperparameter, so you should probably decrease this parameter if you want to avoid the error in the future. I'll edit my previous comment to correct this.

I'll go ahead and close this issue. Feel free to reopen/create a new issue if you still have problems!

**Closed by natsirtguy** 2019-02-26 17:50 UTC

**Comment by dsulkin** [comment] 2019-02-27 15:11
For future reference, is there a way I can troubleshoot any errors running this myself?  Since the Cloudwatch logs don't have a lot of detailed information it's hard to make any progress against problems that I am running into.

Thanks for the help!

**Comment by natsirtguy** [comment] 2019-03-04 17:58
Hi @dsulkin, sorry for the late response. I think your best bet is to keep consulting the tutorials and the docs and opening issues here if you get stuck. The other two tutorials in the Ground Truth folder,

https://github.com/awslabs/amazon-sagemaker-examples/tree/master/ground_truth_labeling_jobs/from_unlabeled_data_to_deployed_machine_learning_model_ground_truth_demo_image_classification

https://github.com/awslabs/amazon-sagemaker-examples/tree/master/ground_truth_labeling_jobs/ground_truth_object_detection_tutorial,

have end-to-end examples of creating labeling jobs and then using the results to train a model using the augmented manifests. Sorry if this isn't quite what you're looking for, but they might be helpful. Good luck!

**Comment by bigunclesolo** [comment] 2020-12-07 20:44
Hello,

Please I have been using a small data set before and achieving a successful training. However, I tried using a lager data set, i kept getting error code

ClientError: Invalid parameter value 'label_width'. Please ensure that the value of parameter 'label_width' is greater than the total number of scalars in annotation data per single image plus header size. See hyperparameters documentation for details. 

![image](https://user-images.githubusercontent.com/66843628/101403289-a20fde00-389a-11eb-9ae4-edbe0582a984.png)

**Comment by PuneethBC** [comment] 2021-01-25 07:48
> I'm running into problems training an Object Detection model using an AugmentedManifestFile that was outputted from GroundTruth.
> 
> I have followed the following examples using the console and the Jupyter notebook.
> 
> * https://docs.aws.amazon.com/sagemaker/latest/dg/augmented-manifest.html
> * https://github.com/awslabs/amazon-sagemaker-examples/blob/master/ground_truth_labeling_jobs/object_detection_augmented_manifest_training/object_detection_augmented_manifest_training.ipynb
> 
> I have ended up with different errors depending on which configuration I use. Below is the collection of configurations and their associated errors I am seeing.
> 
> I have tried doing this in a Jupyter notebook but am ending up with the same combination of errors.
> 
> I am running out of ideas and would really like to get this working. How can I use an augmented manifest file that has been generated from GroundTruth to train a model?
> 
> Here is a sample of the manifest file:
> {"source-ref":"s3://XXXXXX/images/538906508f247.image.jpg","hazmat-job":{"annotations":[],"image_size":[{"width":444,"depth":3,"height":288}]},"hazmat-job-metadata":{"job-name":"labeling-job/hazmat-job","class-map":{},"human-annotated":"yes","objects":[],"creation-date":"2019-02-18T17:11:16.729200","type":"groundtruth/object-detection"}}
> 
> Below are configurations and their errors:
> 
> **Common Configuration**
> 
> * Algorithm source: Amazon SageMaker built-in algorithm
> * Choose an algorithm: Object Detection
> * Input Mode: Pipe
> * Hyperparameters - Used the default and filled in 1 for num_classes and 1 for num_training_samples
> 
> **Configuration 1**
> 
> * Channel Name: "train" or "validation" (i create depending on the channel
> * Input Mode: Pipe
> * Content-Type: left this blank
> * Compression type: None
> * Record Wrapper: RecordIO
> * S3 Data Type: AugmentedManifestFile
> * S3 Data Distribution type: FullyReplicated
> * Augmented Manifest File Attribute Names:  hazmat-job
> 
> **Error**
> 
> * ClientError: Invalid image found. Please ensure data is in one of the expected image formats
> 
> **Configuration 2**
> 
> * Channel Name: "train" or "validation", depending on the channel
> * Input Mode: Pipe
> * Content-Type: left this blank
> * Compression type: None
> * Record Wrapper: RecordIO
> * S3 Data Type: AugmentedManifestFile
> * S3 Data Distribution type: FullyReplicated
> * Augmented Manifest File Attribute Names:  source-ref and hazmat-job
> 
> **Error**
> 
> * ClientError: Got empty batch from pipe. Please check if the manifest file contains valid batches and the value of training job parameter AttributeNames matches attributes names in the augmented manifest.
> 
> **Configuration 3**
> 
> * Channel Name: "train" or "validation", depending on the channel
> * Input Mode: Pipe
> * Content-Type: application/x-recordio
> * Compression type: None
> * Record Wrapper: RecordIO
> * S3 Data Type: AugmentedManifestFile
> * S3 Data Distribution type: FullyReplicated
> * Augmented Manifest File Attribute Names:  source-ref and hazmat-job
> 
> **Error**
> 
> * ClientError: ClientError: Got empty batch from pipe. Please check if the manifest file contains valid batches and the value of training job parameter AttributeNames matches attributes names in the augmented manifest.
> 
> **Configuration 4**
> 
> * Channel Name: "train" or "validation", depending on the channel
> * Input Mode: Pipe
> * Content-Type: application/x-image
> * Compression type: None
> * Record Wrapper: RecordIO
> * S3 Data Type: AugmentedManifestFile
> * S3 Data Distribution type: FullyReplicated
> * Augmented Manifest File Attribute Names:  source-ref and hazmat-job
> 
> **Error**
> 
> * ClientError: ClientError: ClientError: train channel is not specified.
> 
> **Configuration 5 - Based on a solution from AWS forum post**
> 
> * Channel Name: "train" or "validation", depending on the channel
> * Input Mode: Pipe
> * Content-Type: application/x-image
> * Compression type: None
> * Record Wrapper: RecordIO
> * S3 Data Type: S3Prefix
> * S3 Data Distribution type: FullyReplicated
> * Augmented Manifest File Attribute Names:  source-ref and hazmat-job
> 
> **Error**
> 
> * ClientError: ClientError: train channel is not specified.

@dsulkin : With which of the above configs were you able to get it to work finally?
