### ISSUE TITLE
Unable to get output while invoking sagemaker endpoint from .net SDK

### ISSUE THREAD

**Issue by Harathi123** [awslabs/amazon-sagemaker-examples#298] opened 2018-06-29 18:09 UTC
Hi,

We are trying to access the sagemaker endppoint using dot net SDK. Following is the DLL we are using.
AWSSDK.SageMakerRuntime

We are using MXNet_gluon_mnist example in sagemaker python SDK examples.
mnist_mxnet_with_gluon.ipynb
We are sending the byte array as input to the predictor from dot net core.
Content type is 'Application/octet-stream

I changed the transform_fn such that it will accept byte array and convert it into numpy array.
When i tried to invoke endpoint from Sagemaker by giving input as byte array, i am getting output.

But when trying to invoke the same endpoint from .net SDK, we are getting the following error.
"No JSON object could be decoded"

Full Traceback:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/container_support/serving.py", line 180, in _invoke
self.transformer.transform(content, input_content_type, requested_output_content_type)
File "/usr/local/lib/python2.7/dist-packages/mxnet_container/serve/transformer.py", line 62, in transform
return self.transform_fn(self.model, input_data, content_type, accept)
File "/opt/ml/code/mnist.py", line 189, in transform_fn
parsed = json.loads(data)
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")

From the logs, what i understood is it is unable to return output to the .net SDK.
Because, when i tried to debug the transform_fn, its running till end json.dumps() and then again its doing ping check and running back transform_fn. And then its showing the above error.

Any suggestions will be helpful....

Thanks,
Harathi

**Comment by nadiaya** [comment] 2018-06-29 21:22
@Harathi123,

According to traceback the "No JSON object could be decoded" is coming from the user script.

The original transform was doing https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_gluon_mnist/mnist.py#L177-L179

You mentioned you modified transform_fn function. Can you provide the modified user script you used?
The full code including SDK calls would be even more helpful.

**Comment by Harathi123** [comment] 2018-06-29 21:31
@nadiaya, also please find the screenshots for the logs.
By seeing logs, it is evident that the transform_fn function is running till end, but unable to return output (it seems). So, its again doing ping check and running transform function from the beginning.

![2018-06-29](https://user-images.githubusercontent.com/29110281/42115704-e05e874e-7ba8-11e8-9a6d-6266c3167df6.png)
![2018-06-29 1](https://user-images.githubusercontent.com/29110281/42115703-e01c2fa2-7ba8-11e8-8b7f-fafe8fc8541f.png)


))

**Comment by Harathi123** [comment] 2018-07-03 18:41
@nadiaya, thanks for replying

Yes we tried with both content types 'Application/octet-stream' and 'Application/JSON'.
We are trying to invoke endpoint from dot net SDK. The code used to invoke endpoint is as follows:

byte[] content = System.IO.File.ReadAllBytes("E:\\test.png");
  Amazon.SageMakerRuntime.Model.InvokeEndpointRequest request = new Amazon.SageMakerRuntime.Model.InvokeEndpointRequest();
  request.EndpointName = "endpoint name";
  request.ContentType = "application/octet-stream";
  request.Body = new MemoryStream(content);
  AmazonSageMakerRuntimeClient awsClient = new AmazonSageMakerRuntimeClient("access-key", "secret-key", region);
  Amazon.SageMakerRuntime.Model.InvokeEndpointResponse response = await awsClient.InvokeEndpointAsync(request);
 
  string predictions = Encoding.UTF8.GetString(response.Body.ToArray());

We tried with 'Application/JSON' also.
From the logs, it seems the input got loaded to transform function. But getting error while returing output.

Thanks,
Harathi

**Comment by nadiaya** [comment] 2018-07-03 18:52
Could you print the data you get in the transform_fn to see what format is it?

**Comment by Harathi123** [comment] 2018-07-03 19:02
Sorry @nadiaya , the person who is trying to invoke from dot net SDK is working from India. 
But when i tried to invoke it from sagemaker, i am getting output.

**Comment by Harathi123** [comment] 2018-07-03 19:05
We are sending input as follows:
 
Input = list(b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00……………………………’)
The input looks like this:
[137, 80, 78, 71, 13, 10, 26, 10,……………………………]

Thanks,
Harathi

**Comment by Harathi123** [comment] 2018-07-03 19:29
Yes @nadiaya , i am able to run predictions using the endpoint from Sagemaker 'predict' method. But while trying to access same endpoint from dot net SDK, we are getting that error.

**Comment by nadiaya** [comment] 2018-07-03 19:44
So, it seems the problem is that content type is not serialized into JSON when you send using .net SDK. You have to do it explicitly when using AWSSDK.SageMakerRuntime.

And PythonSDK for example handles this serialization for you: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/predictor.py#L59-L94

**Comment by Harathi123** [comment] 2018-07-03 19:53
Yes it seems it is the problem. It means with .net SDK, we need to JSON serialize data before giving it as input. Am i right?

Thanks,
Harathi

**Comment by nadiaya** [comment] 2018-07-03 20:00
Yes, this is correct.
The SageMaker PythonSDK is wrapper on top regular Python AWSSDK (boto) that provides additional functionality to make users life easier.

**Comment by Harathi123** [comment] 2018-07-03 20:32
Ok @nadiaya, thanks for your valuble time and suggestions

**Comment by nadiaya** [comment] 2018-07-03 20:59
I am going to close this issue. Please feel free to reopen it if you have any further questions or problems.

**Closed by nadiaya** 2018-07-03 20:59 UTC
