### ISSUE TITLE
UndefinedModelAttributeError: "serviceId" not defined in the metadata of the model: ServiceModel(sagemaker-runtime)

### ISSUE THREAD

**Issue by C24IO** [awslabs/amazon-sagemaker-examples#459] opened 2018-11-08 00:17 UTC
While running - sagemaker-python-sdk/tensorflow_distributed_mnist/tensorflow_distributed_mnist.ipynb

UndefinedModelAttributeErrorTraceback (most recent call last)
<ipython-input-1-1e2d3f162cfe> in <module>()
      3 from sagemaker import get_execution_role
      4 
----> 5 sagemaker_session = sagemaker.Session()
      6 
      7 role = get_execution_role()

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/session.pyc in __init__(self, boto_session, sagemaker_client, sagemaker_runtime_client)
     77             self.config = None
     78 
---> 79         self._initialize(boto_session, sagemaker_client, sagemaker_runtime_client)
     80 
     81     def _initialize(self, boto_session, sagemaker_client, sagemaker_runtime_client):

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/session.pyc in _initialize(self, boto_session, sagemaker_client, sagemaker_runtime_client)
     98         else:
     99             config = botocore.config.Config(read_timeout=80)
--> 100             self.sagemaker_runtime_client = self.boto_session.client('runtime.sagemaker', config=config)
    101 
    102         prepend_user_agent(self.sagemaker_runtime_client)

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/boto3/session.pyc in client(self, service_name, region_name, api_version, use_ssl, verify, endpoint_url, aws_access_key_id, aws_secret_access_key, aws_session_token, config)
    261             aws_access_key_id=aws_access_key_id,
    262             aws_secret_access_key=aws_secret_access_key,
--> 263             aws_session_token=aws_session_token, config=config)
    264 
    265     def resource(self, service_name, region_name=None, api_version=None,

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/botocore/session.pyc in create_client(self, service_name, region_name, api_version, use_ssl, verify, endpoint_url, aws_access_key_id, aws_secret_access_key, aws_session_token, config)
    807             is_secure=use_ssl, endpoint_url=endpoint_url, verify=verify,
    808             credentials=credentials, scoped_config=self.get_scoped_config(),
--> 809             client_config=config, api_version=api_version)
    810         return client
    811 

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/botocore/client.pyc in create_client(self, service_name, region_name, is_secure, endpoint_url, verify, credentials, scoped_config, api_version, client_config)
     68         service_name = first_non_none_response(responses, default=service_name)
     69         service_model = self._load_service_model(service_name, api_version)
---> 70         cls = self._create_client_class(service_name, service_model)
     71         endpoint_bridge = ClientEndpointBridge(
     72             self._endpoint_resolver, scoped_config, client_config,

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/botocore/client.pyc in _create_client_class(self, service_name, service_model)
     91         class_attributes['_PY_TO_OP_NAME'] = py_name_to_operation_name
     92         bases = [BaseClient]
---> 93         service_id = service_model.service_id.hyphenize()
     94         self._event_emitter.emit(
     95             'creating-client-class.%s' % service_id,

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/botocore/utils.pyc in __get__(self, obj, cls)
    717             return self
    718         else:
--> 719             computed_value = self._fget(obj)
    720             obj.__dict__[self._fget.__name__] = computed_value
    721             return computed_value

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/botocore/model.pyc in service_id(self)
    292     @CachedProperty
    293     def service_id(self):
--> 294         return ServiceId(self._get_metadata_property('serviceId'))
    295 
    296     @CachedProperty

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/botocore/model.pyc in _get_metadata_property(self, name)
    324             raise UndefinedModelAttributeError(
    325                 '"%s" not defined in the metadata of the model: %s' %
--> 326                 (name, self))
    327 
    328     # Signature version is one of the rare properties

UndefinedModelAttributeError: "serviceId" not defined in the metadata of the model: ServiceModel(sagemaker-runtime)

**Comment by sameerbhadouria** [comment] 2018-11-08 18:16
I am seeing this problem too. Tried a few different environments too `conda_mxnet_p27`, `conda_mxnet_p36`, `conda_tensorflow_p27`

**Comment by yangaws** [comment] 2018-11-08 18:52
@sameerbhadouria @C24IO 

We confirmed this error and it should be due to dependent service releasing breaking changes. We have pushed a fix for this. Could you try stopping the current notebook instance and starting it again to get the fix applied? And if errors are no longer there, could you confirm here too?

Thanks!

**Comment by C24IO** [comment] 2018-11-08 18:53
mv  ~/.aws/models/sagemaker-runtime ~/.aws/models/sagemaker-runtime-renamed and restarting the kernel worked for me. Thanks!

**Comment by sameerbhadouria** [comment] 2018-11-08 19:16
@yangaws Works now. Thanks for the quick resolution!

**Comment by C24IO** [comment] 2018-11-10 12:35
@yangaws - lets resolve this if its fixed in the latest build?

**Comment by yangaws** [comment] 2018-11-12 21:10
Close the issue. Feel free to reopen with further questions.

**Closed** 2018-11-12 21:11 UTC
