### ISSUE TITLE
ground truth example fails to copy open-images-dataset

### ISSUE THREAD

**Issue by rudpot** [awslabs/amazon-sagemaker-examples#1085] opened 2020-03-09 19:54 UTC
The ground_truth_labeling_jobs/from_unlabeled_data_to_deployed_machine_learning_model_ground_truth_demo_image_classification demo fails to copy data from the open-images-dataset because of signed requests.

Workaround is get/put copies.

**Comment by TEChopra1000** [comment] 2020-08-17 17:57
@rudpot can you copy and paste the error you saw? I was able to successfully download the data set, and upload it to S3. Did you check that the AWS role or user you were using has permission to copy to S3 - namely s3:GetObject and s3:PutObject?

**Comment by natsirtguy** [comment] 2020-08-28 23:39
I also could not reproduce the error @rudpot saw, `s3.copy` worked for me even though I didn't tell the client to use unsigned requests.

I'll close this for now, feel free to reopen @rudpot if the error still occurs for you.

**Closed by natsirtguy** 2020-08-28 23:39 UTC
