### ISSUE TITLE
Docker file git clone issue

### ISSUE THREAD

**Issue by janvekarnaveed** [awslabs/amazon-sagemaker-examples#1334] opened 2020-07-18 03:37 UTC
I am building a docker container and in the docker file I am building a git package. However, on running the git clone command only partial folders are copied, not all. My dockerfile is as shown below

```
FROM ubuntu:16.04

RUN apt-get -y update && apt-get install -y --no-install-recommends \
         wget \
         python3.5 \
         nginx \
		 libgcc-5-dev \
         ca-certificates \
    && rm -rf /var/lib/apt/lists/*
    
# update and install dependencies
    

RUN wget https://bootstrap.pypa.io/3.3/get-pip.py && python3.5 get-pip.py && \
    pip3 install setuptools numpy==1.14.3 scipy scikit-learn==0.19.1 pandas==0.22.0 flask gevent==1.4.0 gunicorn sklearn boto3 && \
#         (cd /usr/local/lib/python3.5/dist-packages/scipy/.libs; rm *; ln ../../numpy/.libs/* .) && \
        rm -rf /root/.cache


RUN pip3 install cmake
RUN pip3 install --upgrade cython
RUN apt-get update && apt-get install -y build-essential
# RUN pip3 install networkit
RUN apt-get update && apt-get install -y git
# RUN apt-get update && apt-get install -y python3
# RUN git submodule update --init
# RUN git clone https://github.com/networkit/networkit networkit
RUN git clone https://github.com/networkit/networkit.git
RUN cd networkit
RUN ls -l
RUN python3 setup.py build_ext
#RUN pip3 install -e .


# Set some environment variables. PYTHONUNBUFFERED keeps Python from buffering our standard
# output stream, which means that logs can be delivered to the user quickly. PYTHONDONTWRITEBYTECODE
# keeps Python from writing the .pyc files which are unnecessary in this case. We also update
# PATH so that the train and serve programs are found when the container is invoked.

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/program:${PATH}"

# Set up the program in the image
COPY algorithm /opt/program
WORKDIR /opt/program
```

**Comment by mahendruajay** [comment] 2020-08-06 23:59
Not sure why this is an issue inside amazon-sagemaker-examples repository, looks like this is a local Docker issue with cloning git clone https://github.com/networkit/networkit.git

**Comment by aaronmarkham** [comment] 2020-08-07 01:33
> Not sure why this is an issue inside amazon-sagemaker-examples repository, looks like this is a local Docker issue with cloning git clone https://github.com/networkit/networkit.git

Yes, closing this for now. Please re-open with more details if you think the problem is with this repo/project. Thanks!

**Closed by aaronmarkham** 2020-08-07 01:33 UTC
