### ISSUE TITLE
Can I training BlazingText on my local environment?

### ISSUE THREAD

**Issue by knok** [awslabs/amazon-sagemaker-examples#1392] opened 2020-08-12 00:50 UTC
I thinks this is similar to https://github.com/awslabs/amazon-sagemaker-examples/issues/1306 .

I tried to use BlazingText example on my local machine.

I modified to fit sagemaker 2.3.0 the official example:
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/blazingtext_word2vec_text8/blazingtext_word2vec_text8.ipynb
```
import sagemaker
from sagemaker import get_execution_role
import boto3
import json

sess = sagemaker.LocalSession()

# role = get_execution_role()
role = 'role: arn:aws:iam::[$my_id]:user/[$my_account]'
print(role) # This is the role that SageMaker would use to leverage AWS resources (S3, CloudWatch) on your behalf

bucket = sess.default_bucket() # Replace with your own bucket name if needed
print(bucket)
prefix = 'sagemaker/DEMO-blazingtext-text8' #Replace with the prefix under which you want to store the data if needed

train_channel = prefix + '/train'
sess.upload_data(path='text8', bucket=bucket, key_prefix=train_channel)
s3_train_data = 's3://{}/{}'.format(bucket, train_channel)

s3_output_location = 's3://{}/{}/output'.format(bucket, prefix)
region_name = boto3.Session().region_name
# container = sagemaker.amazon.amazon_estimator.get_image_uri(region_name, "blazingtext", "1")
container = sagemaker.image_uris.retrieve("blazingtext", region_name, "latest")
print('Using SageMaker BlazingText container: {} ({})'.format(container, region_name))

bt_model = sagemaker.estimator.Estimator(container,
                                         role, 
                                         # train_instance_count=1, #2, 
                                         instance_count=1,
                                         instance_type='local', #'ml.c4.2xlarge',
                                         # train_volume_size = 5,
                                         # train_max_run = 360000,
                                         input_mode= 'File',
                                         output_path=s3_output_location,
                                         sagemaker_session=sess)

bt_model.set_hyperparameters(mode="batch_skipgram",
                             epochs=5,
                             min_count=5,
                             sampling_threshold=0.0001,
                             learning_rate=0.05,
                             window_size=5,
                             vector_dim=100,
                             negative_samples=5,
                             batch_size=11, #  = (2*window_size + 1) (Preferred. Used only if mode is batch_skipgram)
                             evaluation=True,# Perform similarity evaluation on WS-353 dataset at the end of training
                             subwords=False) # Subword embedding learning is not supported by batch_skipgram

train_data = sagemaker.inputs.TrainingInput(s3_train_data, distribution='FullyReplicated', 
                        content_type='text/plain', s3_data_type='S3Prefix')
data_channels = {'train': train_data}

bt_model.fit(inputs=data_channels, logs=True)
```

the backtrace said:

```
/usr/lib/python3.7/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    485         if check and retcode:
    486             raise CalledProcessError(retcode, process.args,
--> 487                                      output=stdout, stderr=stderr)
    488     return CompletedProcess(process.args, retcode, stdout, stderr)
    489 

CalledProcessError: Command 'docker pull 811284229777.dkr.ecr.us-east-1.amazonaws.com/blazingtext:1' returned non-zero exit status 1.
```

So I tried to invoke docker pull from command line:

```
 % docker pull 811284229777.dkr.ecr.us-east-1.amazonaws.com/blazingtext:1
Error response from daemon: pull access denied for 811284229777.dkr.ecr.us-east-1.amazonaws.com/blazingtext, repository does not exist or may require 'docker login': denied: User:  arn:aws:iam::[$my_id]:user/[$my_account] is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:us-east-1:811284229777:repository/blazingtext
```

It seems I don't have no permission to acees BlazingText ECR repolisory.

Can I use BlazingText training on my local environment?
At least, pytorch_mnist example is worked on my local environment.

**Comment by ChuyangDeng** [comment] 2020-09-16 22:31
Hi @knok,

could you try with:

```
bt_model = sagemaker.estimator.Estimator(container,
                                         role, 
                                         instance_count=1,
                                         instance_type='local', #'ml.c4.2xlarge',
                                         input_mode= 'File',
                                         output_path=s3_output_location,
                                         sagemaker_session=sess,
                                         image_uri="811284229777.dkr.ecr.us-east-1.amazonaws.com/blazingtext:latest")
```

It looks like to be a bug in Python SDK that's retrieving the wrong image uri.

As for the access denied error you got by directly pulling the image, it might be caused by not running the ECR login command `aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com`

**Comment by iyerr3** [comment] 2020-09-18 05:37
This is failing since BlazingText is a 1P algorithm (not framework) and hence not available for `LocalSession`.

**Comment by iyerr3** [comment] 2020-09-27 18:45
Closing the issue as this is by design.

**Closed by iyerr3** 2020-09-27 18:45 UTC
Labels: type: bug
